version: "3.7"

services:
  web:
    image: webdevops/php-apache:8.0-alpine
    container_name: Apache-PHP
    tty: true
    ports:
      - "4500:80"
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      WEB_DOCUMENT_ROOT: /app
    links:
      - database

  database:
    image: mysql:8.0
    container_name: MySQL
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movementRanking
      MYSQL_USER: userBD
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: phpMyAdmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
    ports:
      - "8080:80"
    links:
      - database

volumes:
  mysql-data: